-name: Install IBM MQ

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Disable host key checking
        run: |
          echo "Host *" >> ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Verify SSH key (debug)
        run: |
          ls -l ~/.ssh
          ssh-keygen -lf ~/.ssh/id_rsa

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install ansible -y

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no azcnaresh@20.124.188.123 "echo SSH SUCCESS"

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i hosts.ini mqinstall.yml

